### ISSUE TITLE
Would flowAsync be useful?

### ISSUE THREAD

**Issue by js-choi** [js-choi/proposal-function-helpers#14]
We have `pipe` and `pipeAsync`. We have `flow`. 

Should we have `flowAsync`? 

Are there any precedents from other libraries/languages for a `flowAsync`?

**Comment by samhh** [comment]
Promises aren't monadic, but they're close enough that I think the following rule applies.

When working with monadic (or functorial etc) code it's generally best practice to write your functions to take the simplest dependencies possible. That is, instead of writing a function `Maybe a -> Maybe b`, write a function `a -> Maybe b` and monadic bind at the call site.

The same logic applies to promises. I can't remember the last time I saw a promise taken as a function argument. Where you might have `Promise a -> Promise b`, it's more idiomatic to write it as `a -> Promise b` and simply `.then` chain it. Ergo I'm unsure what the benefit of a `flowAsync` would be; if anything it would only encourage an anti-pattern.

**Comment by lightmare** [comment]
@samhh That's exactly the proposed benefit. If you compose a bunch of async functions with `flow`, they'll receive promises as arguments. Either they don't expect that, or they are the anti-pattern ;)

**Comment by Jopie64** [comment]
Ramda had a similar function [`pipeP`](https://ramdajs.com/docs/#pipeP) but [deprecated it](https://github.com/ramda/ramda/issues/2702) in favor of [`pipeWith`](https://ramdajs.com/docs/#pipeWith) to make it more generic. The nice thing is that it can now be used for more than only promises. As their example:

```js
const pipeWhileNotNil = R.pipeWith((f, res) => R.isNil(res) ? res : f(res));
const f = pipeWhileNotNil([Math.pow, R.negate, R.inc])

f(3, 4); // -(3^4) + 1
```
(this example strangly doesn't show the power of the nil-check every step, but it basically would bailout once a single function returns null)

Suppose there was a similar `Function.flowWith` function. `Function.flowAsync` could then be written as:
```js
Function.flowAsync = (...fs) => Function.flowWith((f, res) => res.then(f), fs);
```
(not tested, so might not be correct, but hopefully the idea is clear.)

As a side-step, I'm not sure about the signature of `R.pipeWith` though... It takes the list of functions as a single array instead of a variadic list of arguments. That probably has to do with the currying nature of Ramda, which also has its upsides, cause you can write `flowAsync` in a point-free way 😊

```js
flowAsync = R.unapply(R.pipeWith((f, res) => res.then(f)));
```

Still I think it would be better when the signature of `Function.flowWith()` would be variadic from it's second parameter like `Function.pipe()`.

**Comment by Avaq** [comment]
@mmkal I think what you're describing is in essence a form of Kleisli Composition, implemented in Ramda as [`pipeK`](https://ramdajs.com/docs/#pipeK).

The idea with the `Symbol('monadishThing')` is essentially what we're doing in [Fantasy Land](https://github.com/fantasyland/fantasy-land) with the [`fantasy-land/chain`](https://github.com/fantasyland/fantasy-land#monad) property (the prefix approximating a Symbol).

I would advice against embedding something like this in the basic `pipe` function, but in a separate function I think it could be nice.

**Comment by ljharb** [comment]
You could also do:
```js
const { result, loading, error } = usePromise(async () => promise1().then(promise2));
```

**Comment by js-choi** [comment]
Normally I wouldn’t include functions that haven’t already been clearly reimplemented and downloaded thousands or millions of times. But `flowAsync` and `pipeAsync` are special, because they are based on two functions that actually have been clearly reimplemented and/or downloaded thousands or millions of times. We want to lubricate working with async functions too, which are built into and privileged by the language (hence my Array.fromAsync proposal too). 

If `flowAsync` is not useful, then `pipeAsync` is also not useful, at least from what I can tell. “Just use `.then`” applies equally to both. So I figure that I’ll propose both…and then remove whatever the Committee pushes strongly back on at plenary.
