### ISSUE TITLE
async pipe semantics

### ISSUE THREAD

**Issue by lightmare** [js-choi/proposal-function-helpers#4]
The code example, together with the following explanation:
> The first sub-function is applied to input and then awaited, then the second sub-function is applied to the first sub-function’s result then awaited, and so forth. In other words, function piping occurs from left to right.

Is inconsistent with the special cases at the end of the explainer:
> If Function.pipeAsync receives only one argument, then it will return Promise.resolve(input) by default.
> If Function.pipeAsync receives no arguments, then it will return Promise.resolve(undefined).

In `await Function.pipeAsync(p)` the promise `p` will be awaited, but in `await Function.pipeAsync(p, f)` it won't.

I would expect the function to behave exactly like:
```js
const asyncPipe = (input, ...fns) => fns.reduce((x, f) => x.then(f), Promise.resolve(input));
// which is consistent with the two special cases (fns.length === 0),
// but not with the preceding description
```

**Comment by lightmare** [comment]
Found a better example showing the issue:
```js
let p = Promise.resolve("done");

Function.pipeAsync(p, console.log);

// should imo give the same output as

Function.pipeAsync(p, Function.identity, console.log);
```

**Comment by runarberg** [comment]
I wonder if `Function.pipeAsync` would be better named `Promise.chain` or `Promise.sequence`. I’ve used this pattern a lot when working with an unknown number of promises which need to be executed in sequence. There is even a pretty popular [Stack Overflow question](https://stackoverflow.com/questions/20100245/how-can-i-execute-array-of-promises-in-sequential-order) about it.

**Comment by js-choi** [comment]
@lightmare: Thanks for pointing out. I totally agree with this change. Pull request is welcome; otherwise, I’ll fix sometime in the next few weeks.

***

@runarberg: There’s some precedent for `fooAsync` being the name for async versions of sync functions in the JavaScript standard and some web standards. These include:

* Atomics.waitAsync (proposal at Stage 3 and shipped in V8)
* Array.fromAsync (proposal at Stage 1)
* WebGPU.mapAsync

So I think `pipeAsync` probably should match those precedents. Hopefully that makes sense.
