### ISSUE TITLE
Debugging and tap callbacks

### ISSUE THREAD

**Issue by js-choi** [js-choi/proposal-function-helpers#8]
@runarberg had a good idea in https://github.com/tc39/proposal-pipeline-operator/issues/225#issuecomment-933705405.

> Just to throw it out there. If debugging is this big of an issue, why hasn’t there been a proposal for say `Function.aside`:
> 
> ```js
> .map(Function.aside(() => { debugger; }))
> ```
> 
> or in the above examples:
> 
> ```js
> await Promise.resolve('intro.txt')
>   .then(Deno.open)
>   .then(Deno.readAll)
>   .then(Function.aside((x) => { console.log(x); debugger; }))
>   .then(data => new TextDecoder('utf-8').decode(data))
>   .then(console.log)
> ```
> 
> Which is rougly:
> 
> ```js
> Function.aside = (fn) => (x) => {
>   fn(x)
>   return x;
> };
> ```
> 
> Prior arts include [Rust’s `inspect`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.inspect), [RxJS’s `tap`](https://rxjs.dev/api/operators/tap). If this is common enough pattern, perhaps it should be included in the [Function helpers proposal](https://github.com/js-choi/proposal-function-helpers).

Debugging in callback-heavy code is a pain. This convenience function would be generally useful. Maybe this should be called `Function.debug` or something. 

My off-work time is currently limited, but I plan to add a section for this sometime in the next few weeks.

Please feel free to comment with more precedents from other languages and libraries here.

**Comment by SRachamim** [comment]
Great idea. `tap` looks like an already widespread name for a function that  performs a side effect with the input value and then returns said input value. (that's the name on RxJs, Ramda and fp-ts, among others).

```typescript
// general definition
Function.prototype.tap = a => { g(a); return this(a); }

/// Example use in a pipe (assume minimal)
```typescript
a
|> f
|> g.tap(console.log)
|> h
```

**Comment by samhh** [comment]
This would be valuable and, being a function, it composes well.

I suspect the overwhelming majority of uses of this function will be for `console.log` calls and `debugger`, in which case we might consider also shipping helpers for those? At which point we'd offer similar functional debugging to Haskell's [Debug.Trace](https://hackage.haskell.org/package/base-4.15.0.0/docs/Debug-Trace.html).

Status quo:

```ts
.map(x => { debugger; return x })
```

`Function.aside` alone:

```ts
.map(Function.aside(() => { debugger }))
```

Specialised helpers (hopefully with better names!) built atop `Function.aside`:

```ts
.map(Function.asideDebug)
```

**Comment by Avaq** [comment]
Added this need, along with mentioned precedents, to the table in #6.

**Comment by js-choi** [comment]
I figure that I’ll add both a `Function.tap(f)` (`x => (f(x), x)`) and a `Function.debug` (`x => { debugger; return x; }`) to the explainer later.

**Comment by boonyasukd** [comment]
Not sure if OOP language precedents matter much here. But here goes nothing...

In Java 8, we have Stream Processing API, which introduces `map()`, `flatMap()`, etc., along with `peek()`. The name is self-explanatory, and it somewhat aligns with `Stack.peek()` which is quite a common data structure API in modern languages:

```java
Stream.of("one", "two", "three", "four")
  .filter(e -> e.length() > 3)
  .peek(e -> out.println("Filtered value: " + e))
  .map(String::toUpperCase)
  .peek(e -> out.println("Mapped value: " + e))
  .collect(toList());
```

In Scala, back in 2018, besides introducing `pipe()`, they also introduced `tap()`, which I believe is in the same spirit as [RxJS, RxPy, Rxrb variants](http://reactivex.io/documentation/operators/do.html). Though in the case of Scala, `pipe()` and `tap()` are at the same level of chaining (not nested under `then()`):

```scala
val x = 1.pipe(plus1)
         .pipe(double)
         .tap(res => println(s"DEBUG: x = $res"))
         .pipe(double)
```

In Kotlin..., besides reusing `peek()` from Java API above, there are also the followings:

- Inside a `Sequence`, we use `onEach()`:

```kotlin
listOf("01", "02", "03")
    .asSequence()
    .onEach { println(it) }
    .filter { it.endsWith("3") }
    .any()
```

- Otherwise, when composing code linearization via [scope functions](https://www.beust.com/weblog/2015/10/30/exploring-the-kotlin-standard-library/), we use `also()`:

```kotlin
// run() + also() if you're `this` lover, 
"16384"
    .run(String::toDouble)
    .run(::sqrt)
    .also(::println)
    .run(Double::toInt)

// let() + also() if you prefer `it` syntax
"16384"
    .let { it.toDouble() }
    .also { doSomethingImpure() }
    .let { sqrt(it) }
    .let { it.toInt() }
    .also { println("The end result is: $it") }
```
